FROM nginx 

MAINTAINER fire7617  version: 0.1

RUN apt-get update -y
RUN apt-get install vim -y


COPY nginx/kiwi-mandgame-admin.local.com.conf /etc/nginx/conf.d/kiwi-mandgame-admin.local.com.conf
COPY nginx/kiwi-mandgame-admin.local.com.conf /etc/nginx/conf.d/kiwi-mandgame-admin.local.com.conf
